### ISSUE TITLE
Videos not written correctly

### ISSUE THREAD

**Issue by bjuncek** [Andrew-Brown1/Automated_Face_Tracking_and_Labelling#15]
When the code runs, only a small percentage of annotated videos is actually written. 
For example when annotation 100 videos, annotations are returned for all 100, but only ~10 videos are written.

**Comment by Andrew-Brown1** [comment]
Hi,

So do I understand correctly that this is when using "--make_annotation_video True" ? 

i.e. using "python VideoFaceAnnotator.py --make_annotation_video True"

**Comment by bjuncek** [comment]
Yes. 

Also, just a note, this will always be True in your current implementation.
You'd probably want to change the bool flags to:
```
parser.add_argument('--store_video', default=False, action='store_true', ...)
```

**Comment by bjuncek** [comment]
Closed -- solved with the update of all packages which leads me to believe there was an ffmpeg issue somewhere which happened silently.
