### ISSUE TITLE
loading senet50_256 model VGGFaceV2

### ISSUE THREAD

**Issue by hanochk** [Andrew-Brown1/Automated_Face_Tracking_and_Labelling#19]
Hi. Im trying to load the latest face embedding model from: https://github.com/ox-vgg/vgg_face2. It seems that the file :senet50_256_pytorch.py is missing in order to load the latest and greatest. Can you help ?
Thanks

**Comment by Andrew-Brown1** [comment]
Hi - are you trying to load the embedding model for use with this repository? 

In the README for this repository, there is information on how to use the face embedding model for use in this repository

**Comment by hanochk** [comment]
Hi, yes, following instruction the senet50... py is missing. I can use the
way it is loaded in the I'd_discriminator. Does face crop resized to
224*224 for that  embedding network ?

**Comment by Andrew-Brown1** [comment]
yes you can load it using the same files in this repo e.g. https://github.com/Andrew-Brown1/Automated_Face_Tracking_and_Labelling/blob/e8964e47892dc23a69e1d5c9b669a724c5079d95/ImageFaceRecognise.py#L50

This repo contains all the processing code necessary to go from an image of a person (not just face) to a face image of the correct form/shape required for the VGGFace2 model  (so yes resizing to 224)
